name: CI/CD React to On-Prem K8s

on:
  push:
    branches:
      - dimitri
    paths-ignore:
      - 'README.md'
    
jobs:
  test-unit:
    runs-on: ubuntu-latest
    container:
      image: node:24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sh ./scripts/setup.sh
      - name: Run unit tests
        run: sh ./scripts/test-unit.sh

  test-sast:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run SAST scan (Semgrep)
        run: sh ./scripts/test-sast.sh
